### ISSUE TITLE
Clarification Required in Irradiation Model - 2

### ISSUE THREAD

**Issue by vikramroybarc** [TarletonGroup/CrystalPlasticity#14]
Dear Eralp,

I would like to express my gratitude for your previous assistance regarding the sintmat2 interaction matrix.

I am currently working on the crss module and have some concerns regarding the code for irradiation model-2.

Specifically, I am uncertain about the interpretation of the values r1, r2, ..., rn, and 'a' mentioned in the documentation. In the file usermaterials.f, rn is defined as follows:
!         defect vectors (crystallographic directions)
irradiationparam(8:10) = (/ 4.0, 6.0, 11.0 /)
Does this imply that r1 = 4.0, r2 = 6.0, and r3 = 11.0? If so, I am perplexed as to how we can define crystallographic directions using only a single real number.

Additionally, in the file, it is stated that 'a' represents the reaction segment and is defined as (a: reaction segment). Does a = 0 indicate that the screw dislocation entirely absorbs the reaction segment, resulting in helical jogs?
I would greatly appreciate your clarification on these matters.

Sincerely,
Vikram

**Comment by EralpDemir** [comment]
Hi Vikram,

Thanks for your interest in the code and your questions about the irradiation model-2. 


Let me try to answer your questions

Q1. Specifically, I am uncertain about the interpretation of the values r1, r2, ..., rn, and 'a' mentioned in the documentation. In the file usermaterials.f, rn is defined as follows:
! defect vectors (crystallographic directions)
irradiationparam(8:10) = (/ 4.0, 6.0, 11.0 /)
Does this imply that r1 = 4.0, r2 = 6.0, and r3 = 11.0? If so, I am perplexed as to how we can define crystallographic directions using only a single real number.


A1. Those number indicate the slip system number (1-12 for FCC) at which defects are dominantly observed. They are real simply because the input parameters are all defined as real(8) type. These number will be converted to integers during the interaction matrix computation (pls. see irradiation.f-line 59). 

A single number is used then we do not have to redefine the slip directions and slip plane normals which would make 6 number of definitions while we are using only 1. It is just to reduce the number of inputs.


Q2. Additionally, in the file, it is stated that 'a' represents the reaction segment and is defined as (a: reaction segment). Does a = 0 indicate that the screw dislocation entirely absorbs the reaction segment, resulting in helical jogs?

Chris Hardie: If a=0 the reaction segment remains in the slip plane. This could be in the form of a helical turn for screw dislocations or a double super jog for edge dislocations

I hope this helps.

Best wishes,
Eralp
