### ISSUE TITLE
Clarification required for Dislocation Hardening in Crystal Plasticity

### ISSUE THREAD

**Issue by vikramroybarc** [TarletonGroup/CrystalPlasticity#15]
Dear Eralp,

I want to express my gratitude for clarifying the doubts I had regarding the irradiation model - 2.

 I  am now facing difficultly in understanding the Dislocation Hardening formulation in the UMAT code.

In many research papers and book on crystal plasticity modeling, I have come across the formulation for Dislocation Hardening as follows:
τ = G12 * b * √(αij * ρj)

This formulation is depicted in the attached screenshot from the book "Dislocations, Mesoscale Simulations and Plastic Flow" by Kubin, published by Oxford.

However, I have noticed that the formulation you provided in the documentation differs from what I have previously encountered. The formulation you presented is:
τ = G12 * b * √(γ^2 * ρ_forest)

Could you please assist me in understanding the differences between these two models?

Here are the screenshots: 
![Screenshot 2023-07-05 212036](https://github.com/TarletonGroup/CrystalPlasticity/assets/126593761/0603530b-dd8a-442f-b619-dab6d9f4173c)

![Screenshot 2023-07-05 212012](https://github.com/TarletonGroup/CrystalPlasticity/assets/126593761/87410b79-a853-45ea-87e7-60b63c6c1561)

Thank you once again for your help.

Sincerely,
Vikram

**Comment by EralpDemir** [comment]
Thanks Vikram.

I agree it is not conventional way of including strength. The developer of the irradiation model did it that way, so we followed his approach. If you look at the forest cut through strength, the factor is just a scalar and it is easy to see why it has a power of two. It is square because when taken outside the parenthesis it is equivalent to the classical factor, A, in strength relation tauc=A G b sqrt(rho). 

In some references, the constant is treated as an interaction parameter inside the square root, as in Kubin's reference and the value of the interaction parameters is of interest, not that it is squared. I found it also a more straightforward. 


The equation in the documentation has a typo that might cause further confusion. I corrected that and sending the correct equation. The loop density is per dislocation type, not per slip system, so the slip system superscript "a" is wrong. That needs to be corrected to the following:


![equation](https://github.com/TarletonGroup/CrystalPlasticity/assets/90987045/4f68e13d-f24f-4a34-8e23-fdc971e11bd9)

If you need to discuss the irradiation model, please contact with Chris Hardie.

I will close this issue with this hoping that it is useful.

Thanks,
Eralp

**Comment by vikramroybarc** [comment]
Thank you, Eralp, for your response.

I have another query regarding dislocation hardening that I would like to discuss with you. The difference between your model and Kubin's model lies in the way the interaction coefficients are modeled.

In Kubin's model, these coefficients are calculated based on dislocation dynamics studies. Also in the kubin model total dislocation density in a slip system is used

 However, in the UMAT model, they are calculated as abs(n_a * t_b)*gf^2. gf being the geometric factor & factor abs(n_a * t_b)  is used to convert total dislocation density to forest dislocation density.

I'm curious to know if there are any studies available that compare the results obtained from these two methods.

I appreciate your assistance once again.

Best regards,
Vikram

**Comment by EralpDemir** [comment]
Hi Vikram,
Thanks for the follow up. 

Yes, exactly. We take into account the projection of GNDs on other systems. This is similar to the reference (https://doi.org/10.1016/j.actamat.2004.04.012)

Alternatively, the interaction coefficients can be used but they are not available for all materials, especially quite complex for bcc and hcp. Therefore, we decided to more straightforward geometric approach while taking into account slip interactions on the strength of the material.

Best wishes,
Eralp
