### ISSUE TITLE
Questions Regarding Hardening Models 3 and 4

### ISSUE THREAD

**Issue by soula039** [TarletonGroup/CrystalPlasticity#32]
Dear Erlap,I'd like to express my sincerest gratitude for your generosity in sharing this invaluable UMAT code. As someone new to the field of crystal plasticity theory, I've come across a few theoretical questions while delving into the documentation and code. I'm hopeful that you can provide some clarifications:

In "slipmodel2," a constant term referred to as the "reference slip rate" is utilized. However, as I've noticed in the relevant literature, this should be related to the evolution of dislocation density. So, I'm considering modifying it to "ρα*b*v0." However, I'm uncertain about what adjustments need to be made in the slip increment calculation process. Additionally, there's some confusion in the documentation regarding dislocation density. For instance, "hardeningmodel3" and "hardeningmodel4" are both related to Kocks-Mecking. Despite reviewing the references you've provided, I've observed that "hardeningmodel4" calculates only the total substructure density as the total dislocation density, excluding forest dislocations. Whereas in "hardeningmodel3," the total dislocation density is equivalent to the total SSD density, and SSD calculations include forest dislocations (assuming GND OFF). I'm curious as to why forest density isn't included in the total dislocation density calculation for "hardeningmodel4".

Furthermore, I've encountered some challenges while using "usermaterials.f." Although the documentation mentions predefined parameters for "alpha-uranium," I've noticed that the "hardeningmodel" for alpha-uranium in "usermaterials.f" is consistently set to 0. Consequently, I've been manually inputting material properties into "PROPS" to use these models. Unfortunately, this approach has resulted in iterative failures in nearly every job run. I would greatly appreciate it if you could provide an example within "usermaterials.f" to demonstrate how to configure material parameters using "hardeningmodel3" and "hardeningmodel4."

Thank you for your assistance.

Warmest regards,
Soula

**Comment by EralpDemir** [comment]
Thanks Soula for the detailed questions.

Let me try to go through one by one:

Q1 In "slipmodel2," a constant term referred to as the "reference slip rate" is utilized. However, as I've noticed in the relevant literature, this should be related to the evolution of dislocation density. So, I'm considering modifying it to "ραbv0." However, I'm uncertain about what adjustments need to be made in the slip increment calculation process. 

A1. There are different version of Kocks thermal activation model is present in the literature. This is one version that has relatively better performance without the presence of athermal stresses. The prefactor gammadot0 is simply a constant but it can also be parametrized as you suggested, the rho in that case is the rhom. But I recommend keeping them constants instead parameters, for example rho being the dislocation density. Otherwise you may encounter convergence issues. If it were kept constant, why not using a single constant though?


Q2. Additionally, there's some confusion in the documentation regarding dislocation density. For instance, "hardeningmodel3" and "hardeningmodel4" are both related to Kocks-Mecking. Despite reviewing the references you've provided, I've observed that "hardeningmodel4" calculates only the total substructure density as the total dislocation density, excluding forest dislocations. Whereas in "hardeningmodel3," the total dislocation density is equivalent to the total SSD density, and SSD calculations include forest dislocations (assuming GND OFF). I'm curious as to why forest density isn't included in the total dislocation density calculation for "hardeningmodel4".
A2. The total density is not used in the strain hardening equations, so it just for outputting. The forest density is projection of dislocations on other systems on the slip system under concern. So adding that would double account for the total density. It is available as a separate output though, it can be added in the post-processing stage if deisred.

Q3. Furthermore, I've encountered some challenges while using "usermaterials.f." Although the documentation mentions predefined parameters for "alpha-uranium," I've noticed that the "hardeningmodel" for alpha-uranium in "usermaterials.f" is consistently set to 0. Consequently, I've been manually inputting material properties into "PROPS" to use these models. Unfortunately, this approach has resulted in iterative failures in nearly every job run. I would greatly appreciate it if you could provide an example within "usermaterials.f" to demonstrate how to configure material parameters using "hardeningmodel3" and "hardeningmodel4."

A3. Alpha-Uranium is an exception in the code, the former user adjusted the model constants manually. It indeed uses hardeningmodel4 but everything is set manually. I have an example that used Kock-Mecking model. I tested it with v2.5 and it works. Sending the .INP file and user fortran files in the zipped. I recommend using usermaterials.f to avoid mistakes.


Hope this helps,
Eralp

[hardeningmodel3.zip](https://github.com/TarletonGroup/CrystalPlasticity/files/13114157/hardeningmodel3.zip)

**Comment by soula039** [comment]
Dear Eralp,
Thank you for providing the examples. I was able to successfully run this case. However, I encountered the following issues when I tried to make some changes only to 'usermaterials.f':

When I used 'hardening model3,' I obtained correct results. However, when I added parameters and switched to 'hardening model4' (using the default parameters from the PDF), 'statev_outputs(2)' consistently showed a value of 0. Is this because of a parameter issue causing the Equivalent Von-Mises plastic strain output to be 0?

I used 'slip model3,' and since 'slipmodel2' and 'slipmodel3' both use the same constant 'gammadot0,' I expected that by adjusting the exponents, I would achieve identical results. I plotted functions and found that they matched perfectly. However, the results obtained from the simulations show significant differences. I would like to understand why this is happening. I've attached the modified 'usermaterials.f'.
![b54593f36f3f90388cfd6df969de699](https://github.com/TarletonGroup/CrystalPlasticity/assets/55824773/f3ed9a9c-27d3-4bfe-be7f-8bf63813f7ba)
![a331c5efdf97247121536ea210b3384](https://github.com/TarletonGroup/CrystalPlasticity/assets/55824773/62556490-ef60-48b9-aa40-e34c2b53c805)
![80c43a9ebd21c79209c2fec2c39c0d9](https://github.com/TarletonGroup/CrystalPlasticity/assets/55824773/2aa418e5-08cd-42eb-865e-9ddcba223fc7)

[usermaterials.zip](https://github.com/TarletonGroup/CrystalPlasticity/files/13166022/usermaterials.zip)
