### ISSUE TITLE
Creep

### ISSUE THREAD

**Issue by nyf-yellow** [TarletonGroup/CrystalPlasticity#34]
Hi Erlap,
  Thanks for sharing the code, It really helps me a lot.
  I have a problem when I test the creep.f in version 2.4. According to the defination of creep, we should test it under a constant load, therefore I apply a constant pressure on the model during Visco analysis step and run it with case(7) in version 2.4. From the result, it seems like there aren't any creep contribution to the slip deformation. I checked the code and the contribution of creep is indeed considered in the code.I'm confused as to why I don't see the corresponding contribution in the results.
  Looking forward to your reply.
Best wishes
Yvfei Nie

**Comment by EralpDemir** [comment]
Hi,
You should turn off slip by setting slipmodel=0 and check if you get creep strains. If the magnitudes are low, that might be reason you are not getting it. You may increase temperature to get an increased effect.

But please make sure to use V2.5 because I remember a correction with creep.

Bests,
Eralp

**Comment by nyf-yellow** [comment]
Hi,
Thanks for your reply. As you suggested, I change to use V2.5 and it did work. Thank you once again, from the bottom of my heart.
Bests,
Yvfei

**Comment by EralpDemir** [comment]
[heart]         Eralp Demir reacted to your message:
________________________________
