### ISSUE TITLE
Why the stress field is non uniform under periodic boundary conditions when considering GND

### ISSUE THREAD

**Issue by akihoo** [TarletonGroup/CrystalPlasticity#37]
Hi Eralp,

I'm testing the periodic boundary conditions (PBC) by using a single crystal tensile case. 

In the first case, I use the power law model, Voce hardening model, GND model (no backstress model). Everything goes well at the elastic and the small plastic period (Figure a); the stress field is uniform. However, the stress gradually becomes nonuniform with the increasing plastic strain. At first, the difference between the maximum and minimum stress is neglectable (<1e-3 MPa in Figure b), while the difference will increase to 1MPa with the increase of plastic strain. Obviously, this result is wrong because the stress field should be uniform under the PBC. I have also tried the Explicit/Implicit method, and the stress field are both nonuniform.

<img width="974" alt="image" src="https://github.com/TarletonGroup/CrystalPlasticity/assets/14359322/71bf3819-f216-4c87-891d-9faaef263892">

To understand what happened, I ran the second simulation with the same model setting, except the GND model was off. To my surprise, the result I obtained is a uniform stress field. 

I'm curious about what happened to the GND model that led to a nonuniform stress field. Based on the model I selected, the GND is not involved in the slip and hardening model, so the calculation of the GND will not influence the slip and hardening process. Could you advise me on obtaining a uniform stress field under PBC with GND?

Bests,
Feiyu

**Comment by EralpDemir** [comment]
Hi Feiyu,
I think you may expect this since GNDs are calculated explicitly. I am not sure how to avoid this or if it is possible to avoid it happening. 

The gradient calculations by its nature involves extrapolation and interpolation, very small differences might be amplified over small distances due to the gradients. If you want a perfectly uniform stress field, you may try to put size dependence phenomenologically to tauc.

Bests,
Eralp
