### ISSUE TITLE
the output file 

### ISSUE THREAD

**Issue by mcren1** [TarletonGroup/CrystalPlasticity#38]
Hi Eralp,
When I'm printing "Crystal to Sample tranformation: statev_gmatinv" that is data statev_outputs(1),a problem was encountered . The 9 parameters of the rotation matrixwere indeed non-zero, corresponding to the last frame output after load. But the initial rotation matrix of the polycrystalline model with Euler Angle information  had 9 zeros. I have the euler Angle and rotation matrix information of the initial polycrystalline model. How can I get the real final Euler Angle information through the SDV 1-9 output by abaqus? Is it through the rotation matrix output by abaqus plus the identity matrix, and then multiplied by the initial Euler Angle rotation matrix, or by other ways?
 I would be extremely grateful for any insights, advice, or recommended resources you can offer.

[Uploading initial transformation matrix output by abaqus.csv…]()

Best,
Mengchong Ren

**Comment by EralpDemir** [comment]
Hi Ren,

At the first increment the material information is read for each element.  This is done to allow use of different materials in the mesh. So that is why it is zero at the first increment.

If you like to see the Euler angles and orientations, you may try outputting some results at the initialization within the subroutine initialize_orientations using "write(*,*)" command.

Bests,
Eralp

**Comment by mcren1** [comment]
Hi,
Thanks a lot. I truly appreciate your assistance.

Bests,
Mengchong Ren
