### ISSUE TITLE
Clarification Required in File CRSS.f

### ISSUE THREAD

**Issue by vikramroybarc** [TarletonGroup/CrystalPlasticity#47]
Subject: Query Regarding Geometric Factor in CRSS.f Implementation

Dear Eralp,

I hope this message finds you well. I am currently reviewing the implementation of CRSS.f and have a specific question that I would appreciate your assistance in clarifying.

![code25](https://github.com/TarletonGroup/CrystalPlasticity/assets/126593761/f8f2d19e-156f-462c-a528-a20846934bad)

In the code snippet provided, there is a parameter referred to as the "geometric factor," and its value is typically set around 0.25, as indicated in the usermaterials.f file.

Traditionally, the calculation of CRSS from dislocations involves the use of an interaction matrix. I'm curious about why this geometric factor is employed in the current implementation and whether it is somehow related to the Taylor factor.

Additionally, I am interested in understanding how one determines the appropriate values for this geometric factor. Could you provide insights or guidance on this matter?

Your clarification on these points would be immensely helpful in deepening my understanding of the code.

Thank you for your time and consideration.

Best Regards,
Vikram Roy

**Comment by EralpDemir** [comment]
Hi Vikram,

It is a good question. In some references it is called the strength coefficient. I have learned as the geometric factor.


It is a single factor that adjust how the average spacing between the dislocations reflect to the strength. 

An interaction matrix can also be used instead of this factor. But in that case all the strength interactions shall be determined between the slip systems. In our case we have edge and screw type dislocations which makes it even challenging. When you consider hcp or bcc materials that would make a 30x30 or 48x48 matrix of numbers. Therefore, we simply ignore these individual interactions.

This constant simply allows us to calibrate the strength, especially the yield point, for these kind of models while keeping the initial densities in reasonable magnitudes. 

I hope this clarifies. I may recommend this paper for further reading and you may find Taylor equation in books:
https://doi.org/10.1016/S1359-6454(00)00289-5

Hope this helps,
Eralp
