### ISSUE TITLE
Query related to phenomenological and dislocation models 

### ISSUE THREAD

**Issue by kushwaha-ajay** [TarletonGroup/CrystalPlasticity#49]
I had a query related to the understanding of the hardening models. 

1. The voce hardening model (hardening model = 1) is considered to be a phenomenological model. Is the Kocks-Mecking model (hardening model = 3 and 4) considered a dislocation-based model or a phenomenological model? Some literature mentions it as a dislocation-based model; however, some consider it to be a phenomenological model, as dislocation densities are calculated using the Taylor equation. 

2. After calibrating the model to fit the stress-strain response the same as the experimental tensile curve for both models (1 and 4), the field output distribution of stress, strain, and total slip per system on the RVE appears to be more or less the same. What differences could be expected in the results from both models?

Regards,
Ajay

**Comment by EralpDemir** [comment]
Hi again,

1. Some consider KM hardening as phenomenological model since it involves parameter fitting. But nearly all models have some constants to fit. However, dislocation evolution equations that are based on reactions have been referred as physical models.

2. If you would like to have a model that uses dislocation density as a state variable, model-4 can provide an evolution law for that. Otherwise phenomenological models as you mention provide enough freedom.

Best,
Eralp
