### ISSUE TITLE
Incomprehension about the form of creep damage function in creep.for

### ISSUE THREAD

**Issue by pico520m** [TarletonGroup/CrystalPlasticity#50]

**Comment by pico520m** [comment]
Dear Eralp
It is fortunate to have met the achievements you have made, which have been of great help to my current research。I am currently studying the creep behavior of metal materials from a macro to a micro perspective. Looking at the creep of single crystals, the most commonly used equation is the slip system Norton equation, which is usually combined with the KR damage model to achieve the damage evolution of different slip systems. 

Of course, exponential equations or sinh can also fit creep curves. However, I still don't quite understand the damage evolution of the exponential creep equation. It seems that the creep rate and the damage induced creep rate are  parallel relationships rather than coupled relationships. In a mathematical way, it seems like：
![屏幕截图 2024-04-08 190932](https://github.com/TarletonGroup/CrystalPlasticity/assets/154584861/6161044a-6657-44cf-a12b-ad8556f8256e)

 I wonder if  there’s any paper for reference or suggeestion that can help us better understand the equation and fit the parameters.

Looking forword to your reply.

Best wishes,
 Joe Chen

**Comment by EralpDemir** [comment]
Thanks Joe for your interest, happy to help, open to collaborate as well.

The creep equation in the code is almost the same as you have shown but with creep damage being a function of cumulative slip instead of norm of the  Lp.

This is a good reference for the creep equations:
https://doi.org/10.1016/j.ijplas.2023.103589

You may further find references from that paper.

Best,
Eralp
