### ISSUE TITLE
question about GND model

### ISSUE THREAD

**Issue by AliceNeper** [TarletonGroup/CrystalPlasticity#79]
Hello Enrlalp，I have a question about the GND model. Why does the value of GND start from 0 every time? Shouldn't your material have some GND to coordinate the deformation of grain at the beginning？Where can I modify the initial dislocation density.
Looking forward to your answer,thank you!

**Comment by EralpDemir** [comment]
Hi,
GNDs change with the lattice curvature. It is not possible to quantify that initially.

If you have measured initial GND density, you may assign it as initial density by reading a file or st. We just did not do it  because it is usually computed wrong from EBSD maps by using L2 method giving GND density nearly in all slip systems which leads to possible convergence issues and wrong findings.

Best,
Eralp
